version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nestdb
    volumes:
      - mongo_data:/data/db

  nestjs-app:
    build: .
    container_name: nestjs-app
    ports:
      - "${HTTP_PORT:-3000}:3000"
    environment:
      HTTP_HOST: ${HTTP_HOST:-localhost}
      HTTP_PORT: ${HTTP_PORT:-3000}
      MONGO_URL: mongodb://mongo:27017/nestdb
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command:  npx nodemon --watch src --legacy-watch --exec "npm run start:dev"

volumes:
  mongo_data:
